[package]
name = "Appendage"
description = "Append text to files without all of the hassle"
version = "0.1.0"
authors = ["michal <michal@tar.black>"]
edition = "2021"
license = "GPL-3.0"

[[bin]]
name = "apd"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }